### ISSUE TITLE
Container and When Statements

### ISSUE THREAD

**Issue by danielkinguk** [ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang#28]
"What is not clear with the model is the first container and the when statement. As another YANG doctor explained, the when-stmt applies to *instances* of a model, not to the schema. Therefore a when-stmt that points back to a node that is part of schema and is a presence container does not achieve what I think the authors intended, i.e. a when condition."

Having looked at other examples, several CCAMP documents make use of "when" statements, but non-CCAMP I-Ds do not. Do we really need the "when" statement? To me “when” might apply to a data object, such as “true” “false” “3”, etc.

**Comment by danielkinguk** [comment]
We should also check usage for WSON I-D. 

WSON YANG Dr Review - https://datatracker.ietf.org/doc/review-ietf-ccamp-wson-yang-15-yangdoctors-lc-lindem-2018-11-13/
WSON https://datatracker.ietf.org/doc/html/draft-ietf-ccamp-wson-yang-15 in version 15 they commented out.

**Comment by danielkinguk** [comment]
Dan to check with NETMOD, but it looks like a legitimate use of the "when" statement as applied other TE documents.

**Comment by italobusi** [comment]
Aihua and I have made some checks on:

https://stackoverflow.com/questions/5689966/how-to-check-if-an-element-exists-in-the-xml-using-xpath/5690522

https://www.w3.org/TR/1999/REC-xpath-19991116/#booleans

It seems to us that the current when statements are correct since the boolean () XPath function is automatically applied and it returns true when the node exists

However, it is still good to double check with NETMOD

**Comment by danielkinguk** [comment]
<tp>
I commented before that I struggle with the complexity of the 'when' statements in many CCAMP and TEAS I-D such as this one.

Is it
      when "../../../../../../../../../../"
          + "nw:network-types/tet:te-topology/"
 or
      when "../../../../../../../../../"
          + "nw:network-types/tet:te-topology/"
 or
      when "../../../../../../../nw:network-types/tet:te-topology/"

? answer all of them depending!

I speculated that the absolute form of the path statement would be much simpler but it was pointed out to me by Martin that that would not work as 'nw:network is a list and so would return true if 'flexi-grid-topology' appeared anywhere in the list which in this case it is almost bound to; but there is the XPath 'ancestor' function which returns true only if the value appears in an immediate ancestor of the context node.  This is almost what I want the caveat being that it returns true if any of the predicates - e.g. primary-path, route-object-exclude-object, etc -  has the value  in question but I believe that that will never be the case.

In which case,
 when "ancestor::node()/nw:network-types/tet:te-topology"
as proposed by Lada will do the job for almost all the 'when' statements (and I can understand it ).

The thread is on the netmod WG list from 29dec21 under the subject
YANG 'when' with absolute path

Tom Petch

**Comment by danielkinguk** [comment]
Lets investigate use of xpath ancestor (parent/grandparent) see: 

https://www.educba.com/xpath-ancestor/

How widespread is this function in IETF YANG modules? 

Sergio and Italo will inspect further and we will also need to check with other similar implementations.

**Comment by italobusi** [comment]
YANG model updated but we have found some issues with yanglint compilation:

https://mailarchive.ietf.org/arch/msg/netmod/SvYTvbqNEeBT5IL74xtDQYwfy_A/

**Comment by danielkinguk** [comment]
Pyang compilation does not return any error/warnings, but when we use yanglint we see errors as it does recognize ancestor statements. 

Response from Michal Vaško <mvasko@cesnet.cz> Tue, 18 January 2022 07:07 UTCShow header

>>
Hi,

yanglint uses its own XPath implementation, which unfortunately does not support axes, hence the error.

Regards,
Michal
<<
 We

**Comment by danielkinguk** [comment]
YANG experts have confirmed the YANG xpath axes ancestor structure and function is reasonable, but not widely used in other IETF modules, and we can ignore the libyang compilation errors due to a lack of support for axes.  

We will summerise the situation with WG and ask other implementers for feedback. 

- Dan to email CCAMP WG for flexi-grid module feedback
- All, decide if we should present an update on the issue to NETMOD and/or CCAMP at IETF 113 (March)

**Comment by danielkinguk** [comment]
An ongoing discussion with NETMOD and tools team Re: XPATH ancestor function. Although the NETMOD team is not negative towards using ancestor function in our model(s), the tools are not able to cope with the function, and we may need to revert ro a more conservative approach.
