### ISSUE TITLE
Augmentation Statements

### ISSUE THREAD

**Issue by danielkinguk** [ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang#29]
"The second general comments has to do with the 80 augment statements. As an operator, I would find it very tedious to configure this model, what with 80 different XPaths to follow. Would it not be better to gather all the augmenting (flexi-grid) parameters together and use leafrefs to link these data structures to the ietf-network module?"

This does seem like a valid comment? When wandering down the branches of the tree, why not add a whole new branch augmentation with the new objects in a single branch augmentation, instead of lots of augmentations?

**Comment by dperdices** [comment]
To provide more information, the actual version follows the example provided in RFC8795, see https://datatracker.ietf.org/doc/html/rfc8795#appendix-C.

**Comment by italobusi** [comment]
This issue was discussed upfront with Netmod WG:

https://mailarchive.ietf.org/arch/msg/netmod/-6L8KYVVhFiS8KpmH2fUpBmdSy8/

Appendix C of RFC8795 is based on the feedbacks received from Netmod WG.

**Comment by danielkinguk** [comment]
Continued in issue #28
