### ISSUE TITLE
LC Review from Tom

### ISSUE THREAD

**Issue by danielkinguk** [ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang#40]
<tp>
wrong YANG  prefix (s.9)

After all the discussions on CCAMP and TEAS WG lists about what would make for a good prefix, this does not bode well - sigh

<tp2>
And while I am on the admin ...

The dates ib the module are wrong but differently wrong in different places - if it were all the same wrong I would live with it.

Security Considerations make no mention of any nodes in this I-D - I doubt if the AD will countenance that.

RFC Editor Note Please replace XXXX with the numbers assigned to RFC9093 Really?  Look in the YANG module revision reference and you may think again

TLP is out of date

Copyright out of date  - perhaps 2022!

URL lack security (https:) in several places

URL to an obsolete web page (tool)

[G.694.1] .... G-872
Really?

As I have commented before, it is a pig to review because TE got its YANG structure wrong in the first place so whether or not I will look at the semantics of the model , I do not know - perhaps if Boxing Day gets very boring:-)

**Comment by danielkinguk** [comment]
2. For "RFC XXXX" and "RFC YYYY" need to check usage within I-D for consistency 
3. IANA Section referred to old prefix. 

OLD
   IANA is requested to assign a new YANG module name in the "YANG
    Module Names" registry [RFC6020] as follows:

          Name: ietf-flexi-grid-topology
          Namespace: urn:ietf:params:xml:ns:yang:ietf-flexi-grid-topology
          Prefix: flexi-grid-topology
          Reference: [This.I-D]
NEW
   IANA is requested to assign a new YANG module name in the "YANG
    Module Names" registry [RFC6020] as follows:

          Name: ietf-flexi-grid-topology
          Namespace: urn:ietf:params:xml:ns:yang:ietf-flexi-grid-topology
          Prefix: flexgt
          Reference: RFC XXXX

4. Need to check how we reference an ITU-T amendment.

5. Security issues in code

6. URL usage should be "https"

7. Time to move from "Informational" to "Standards Track"? Italo to raise on list. 

Also waiting on additional comments from LC.

**Comment by italobusi** [comment]
> TLP is out of date

What is the meaning of TLP?

**Comment by danielkinguk** [comment]
Oh, wonder if its "Trust Legal Provisions" in YANG code. "Copyright (c) 2020 IETF Trust and the persons identified as authors of the code"

**Comment by italobusi** [comment]
then it should be fixed by the YANG model update in https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang/commit/c8710322327eb1d974b2dd0075bed3eaf807522d
