### ISSUE TITLE
Muxponders' configuration constraints

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang#56]
During ACTN POI discussion, it has been noted that "in MXPs usually the client ports are assigned to the time slots by default (or by design)".

See: https://github.com/FabioPeruzzini/actn-poi/issues/108

If the muxponder can constraint which client ports can be connected together, this constraint shall be reported to the MDSC through the MPI but this information is not defined in the existing topology YANG models.

It is not yet clear how this constraint can be reported and whether this information should be reported by the flexi-grid topology model (e.g., a V2 version of the model) or by the optical impairments topology model

**Comment by danielkinguk** [comment]
Need to decide what information/attributes to report and then update the model/document.

**Comment by italobusi** [comment]
Slide discussed during the meeting:

The inter-layer lock indicates that the 10 LTPs on node A (or node Z) can be connected to a WDM tunnel starting from the TTP in node A (or in node Z, respectively)

If at least one of the two muxponders support a flexible multiplexing label allocation, the 10GE service between MXP-A-1 and MXP-Z-5 is feasible

If the two muxponders support a fixed multiplexing label allocation, the 10GE service between MXP-A-1 and MXP-Z-5 is not feasible while the 10GE service between MXP-A-1 and MXP-Z-1 is feasible.

From the inter-layer lock information it seems possible to setup a 10GE service between MXP-A-1 and MXP-Z-5, so additional information is needed to report when there are additional constraints that make it not possible

In many cases the multiplexing label is proprietary. It is therefore also important to check that the two muxponders support the same multiplexing label. The type of multiplexing label can also report whether the label allocation is fixed or flexible.

In order to report the type of multiplexing label, it has been agreed to re-use the switching-capability*  with vendor-specific values for vendor-proprietary multiplexing types

However, even if the type of multiplexing label reports that the label allocation is fixed, the information about which LTP is associated with which label or muxponder physical port is still missing

**Comment by italobusi** [comment]
When the the mapping/multiplexing technology is proprietary, the two muxponders shall be under the control of the same PNC so any proprietary configuration can be managed by the PNC with no need to be exposed at the MPI toward the MDSC. However, these constraints have an impact on the pair of LTPs the MDSC can request the service setup and therefore it is worthwhile to expose it at the MPI through a standardized YANG model

However, the solution should be generic enough not to depend on any specific standard or proprietary mapping/multiplexing technology

Proposed resolution:

```
       +--rw termination-point* [tp-id]
         +--rw tp-id?   ...
         +--rw te-tp-id?   te-types:te-tp-id
         +--rw te!
            ...
            +--rw inter-layer-lock-id*              uint32
            +--rw inter-layer-sequence-number?      uint32

```

**Comment by danielkinguk** [comment]
This capability will be discussed/documented in Optical Impairments I-D. https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/120

**Comment by danielkinguk** [comment]
Waiting on Dieter, Sergio and Aihua to propose some text for the Optical Impairment I-D that can be references from the Flexi-Grid work.

**Comment by italobusi** [comment]
Close with https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-optical-impairment-topology-yang/issues/120
