### ISSUE TITLE
Support for a single and multiple topology instance across multi-layer networks

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang#57]
It seems that there are gaps when the current flexi-grid topology model is used to support a single topology instance across multi-layer networks, using network types multi-inheritance.

For example, it might be possible to use multi-inheritance to expose a single topology instance across flexi-grid, OTN and ETH networks:

```
      |  +--rw tet:te-topology!
      |     +--rw flexigt:flexi-grid-topology!
      |     +--rw otnt:otn-topology!
      |     +--rw eth-tet:eth-tran-topology!
```

**Comment by italobusi** [comment]
2023-01-26 Flexi-grid call

Some details about the issues identified with the current flexi-grid, OTN and ETH topology models, as discussed during the audio today:

[current-ml-topology-models-00.txt](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang/files/10510413/current-ml-topology-models-00.txt)

Some initial brainstorming analysis for possible options to resolve di issue, , as discussed during the audio today:

[new-ml-topology-models-00.txt](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang/files/10510430/new-ml-topology-models-00.txt)

**Comment by danielkinguk** [comment]
Created topology examples for single instance and multiple topologies over multi-layer networks. 

[MLN Topologies v1.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang/files/10795135/MLN.Topologies.v1.pptx)

**Comment by danielkinguk** [comment]
Updated use cases. 

[MLN.Topologies.v2.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang/files/10871263/MLN.Topologies.v2.pptx)

**Comment by italobusi** [comment]
It is worth noting that the flexibility to support either multiple single-layer topology instances or a single multi-layer topology instance (see slides 6 and 4 in https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang/files/10871263/MLN.Topologies.v2.pptx) is similar to the options for GMPLS as described in RFC 5212 (thanks to @sergiobelotti for the reference)
