### ISSUE TITLE
Working Group update on open issues and proposed resolution of Flexi-Grid Topology

### ISSUE THREAD

**Issue by danielkinguk** [ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang#59]
A few slides summarising the current issues affecting the Flexi-Grid topology document.  
[Open Issues for Flexi-Grid v2.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang/files/10756205/Open.Issues.for.Flexi-Grid.v2.pptx)

**Comment by danielkinguk** [comment]
Proposed email to AD, Chairs and Working Group. 

>>
Dear John, Chairs and Working Group, 

As you know, the authors of the Flexi-Grid Topology requested to pause the document (before the AD Review) as additional requirements were proposed that would require a substantive change to the Flexi-Grid Topology I-D (draft-ietf-ccamp-flexigrid-yang).

Several authors of the affected I-Ds and related documents have concluded our analysis. We feel a new solution (YANG model) must address new requirements for mixed technology environments. Furthermore, we have highlighted these requirements in four key uses. The new requirements and use cases are documented in the following GitHub issue (57):

https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang/issues/57

We will provide a more detailed update during the CCAMP session at IETF 116, including the following:

1.	A summary of the new requirements and use cases
2.	Which documents are affected?
3.	What we intend to do with the affected documents (modify or restart them)
4.	Provide an overview of the new (or modified) YANG model(s) to address the requirements and use case scenarios
5.	Will this affect previous SDO Liaisons, and what SDO communication may be required moving forward 
6.	Propose a sequence of actions and the next steps

We can then receive feedback from the wider CCAMP community. 

BR, Dan (on behalf of the Flexi-Grid discussion participants)  
<<

**Comment by danielkinguk** [comment]
Version 3 of the requirements and use case, slides. 

[MLN.Topologies.v3.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang/files/10872173/MLN.Topologies.v3.pptx)

**Comment by italobusi** [comment]
> Version 3 of the requirements and use case, slides.
> 
> [MLN.Topologies.v3.pptx](https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang/files/10872173/MLN.Topologies.v3.pptx)

I would suggest to remove (or to move in backup) the physical layer topology cases:
- it is a new, potentially controversial, requirement which still needs to be discussed and could cause unnecessary opposition to the work; 
- it increases the number of scenarios causing loss of focus on the urgent requirements we need to be addressed; 
- if we are able to update the current models to be more modular, adding the physical topology in a modular way at a later stage will not be an issue
