### ISSUE TITLE
Name for the channel spacing type

### ISSUE THREAD

**Issue by sergiobelotti** [ietf-ccamp-wg/draft-ietf-ccamp-flexigrid-yang#71]
There is a wrong definition in 9093 about channel spacing in the context of flexible grid. 
See the issue in RFC9093-bis https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis/issues/56

**Comment by italobusi** [comment]
Need to import the l0-types from RFC9093-bis: this creates a dependency between the flexi-grid topology and RFC9093-bis

**Comment by italobusi** [comment]
YANG model updated in PR #70 

Need also to update the reference in the I-D: to be discussed with @danielkinguk

**Comment by italobusi** [comment]
> Need also to update the reference in the I-D: to be discussed with @danielkinguk

- [ ] @italobusi : update the I-D accordingly
